title: i2c Lab
subtitle: Invention and Innovation in Computing for Sustainable Development
description: An engaging 1-3 sentence description of your lab.
header: images/background.jpg
footer: images/background.jpg
links:
  email: rabimba@rabimba.me
  orcid: 0000-0001-8713-9213
  google-scholar: PYmmdne2aRMC
  github: rabimba
  twitter: rabimba
  youtube: rabimba
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@rabimba.com
github: rabimba
twitter: rabimba
instagram: rabimba
youtube: rabimba
