- id: doi:10.48550/arXiv.2301.00665  
  image: https://i1.rgstatic.net/publication/366821330_Targeted_Phishing_Campaigns_using_Large_Scale_Language_Models/links/63b39e39a03100368a4b3cf4/largepreview.png

